import Head from "next/head";
import { ArticleList, Articles } from "@components/templates";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArticleList posts={posts} />
    </>
  );
}

export const getServerSideProps = async () => {
  return {
    props: {
      posts: ["message"],
    },
  };
};
